export default [
  // Vowels
  {
    id: 'kana-a',
    hiraganaPath: './hiragana-a.svg',
    katakanaPath: './katakana-a.svg',
    name: 'a',
    family: 'vowel',
  },
  {
    id: 'kana-i',
    hiraganaPath: './hiragana-i.svg',
    katakanaPath: './katakana-i.svg',
    name: 'i',
    family: 'vowel',
  },
  {
    id: 'kana-u',
    hiraganaPath: './hiragana-u.svg',
    katakanaPath: './katakana-u.svg',
    name: 'u',
    family: 'vowel',
  },
  {
    id: 'kana-e',
    hiraganaPath: './hiragana-e.png',
    katakanaPath: './katakana-e.svg',
    name: 'e',
    family: 'vowel',
  },
  {
    id: 'kana-o',
    hiraganaPath: './hiragana-o.svg',
    katakanaPath: './katakana-o.svg',
    name: 'o',
    family: 'vowel',
  },
  // K-Family
  {
    id: 'kana-ka',
    hiraganaPath: './hiragana-ka.svg',
    katakanaPath: './katakana-ka.svg',
    name: 'ka',
    family: 'K',
  },
  {
    id: 'kana-ki',
    hiraganaPath: './hiragana-ki.svg',
    katakanaPath: './katakana-ki.svg',
    name: 'ki',
    family: 'K',
  },
  {
    id: 'kana-ku',
    hiraganaPath: './hiragana-ku.svg',
    katakanaPath: './katakana-ku.png',
    name: 'ku',
    family: 'K',
  },
  {
    id: 'kana-ke',
    hiraganaPath: './hiragana-ke.svg',
    katakanaPath: './katakana-ke.png',
    name: 'ke',
    family: 'K',
  },
  {
    id: 'kana-ko',
    hiraganaPath: './hiragana-ko.svg',
    katakanaPath: './katakana-ko.png',
    name: 'ko',
    family: 'K',
  },
  // N-Family
  {
    id: 'kana-na',
    hiraganaPath: './hiragana-na.svg',
    katakanaPath: './katakana-na.png',
    name: 'na',
    family: 'N',
  },
  {
    id: 'kana-ni',
    hiraganaPath: './hiragana-ni.svg',
    katakanaPath: './katakana-ni.png',
    name: 'ni',
    family: 'N',
  },
  {
    id: 'kana-nu',
    hiraganaPath: './hiragana-nu.svg',
    katakanaPath: './katakana-nu.svg',
    name: 'nu',
    family: 'N',
  },
  {
    id: 'kana-ne',
    hiraganaPath: './hiragana-ne.svg',
    katakanaPath: './katakana-ne.png',
    name: 'ne',
    family: 'N',
  },
  {
    id: 'kana-no',
    hiraganaPath: './hiragana-no.svg',
    katakanaPath: './katakana-no.png',
    name: 'no',
    family: 'N',
  },
  // M-Family
  {
    id: 'kana-ma',
    hiraganaPath: './hiragana-ma.svg',
    katakanaPath: './katakana-ma.png',
    name: 'ma',
    family: 'M',
  },
  {
    id: 'kana-mi',
    hiraganaPath: './hiragana-mi.svg',
    katakanaPath: './katakana-mi.png',
    name: 'mi',
    family: 'M',
  },
  {
    id: 'kana-mu',
    hiraganaPath: './hiragana-mu.svg',
    katakanaPath: './katakana-mu.png',
    name: 'mu',
    family: 'M',
  },
  {
    id: 'kana-me',
    hiraganaPath: './hiragana-me.svg',
    katakanaPath: './katakana-me.png',
    name: 'me',
    family: 'M',
  },
  {
    id: 'kana-mo',
    hiraganaPath: './hiragana-mo.svg',
    katakanaPath: './katakana-mo.png',
    name: 'mo',
    family: 'M',
  },
  // R-Family
  {
    id: 'kana-ra',
    hiraganaPath: './hiragana-ra.svg',
    katakanaPath: './katakana-ra.png',
    name: 'ra',
    family: 'R',
  },
  {
    id: 'kana-ri',
    hiraganaPath: './hiragana-ri.svg',
    katakanaPath: './katakana-ri.png',
    name: 'ri',
    family: 'R',
  },
  {
    id: 'kana-ru',
    hiraganaPath: './hiragana-ru.svg',
    katakanaPath: './katakana-ru.png',
    name: 'ru',
    family: 'R',
  },
  {
    id: 'kana-re',
    hiraganaPath: './hiragana-re.svg',
    katakanaPath: './katakana-re.png',
    name: 're',
    family: 'R',
  },
  {
    id: 'kana-ro',
    hiraganaPath: './hiragana-ro.svg',
    katakanaPath: './katakana-ro.png',
    name: 'ro',
    family: 'R',
  },
  // S-Family
  {
    id: 'kana-sa',
    hiraganaPath: './hiragana-sa.svg',
    katakanaPath: './katakana-sa.svg',
    name: 'sa',
    family: 'S',
  },
  {
    id: 'kana-shi',
    hiraganaPath: './hiragana-shi.svg',
    katakanaPath: './katakana-shi.png',
    name: 'shi',
    family: 'S',
  },
  {
    id: 'kana-su',
    hiraganaPath: './hiragana-su.svg',
    katakanaPath: './katakana-su.png',
    name: 'su',
    family: 'S',
  },
  {
    id: 'kana-se',
    hiraganaPath: './hiragana-se.svg',
    katakanaPath: './katakana-se.png',
    name: 'se',
    family: 'S',
  },
  {
    id: 'kana-so',
    hiraganaPath: './hiragana-so.svg',
    katakanaPath: './katakana-so.png',
    name: 'so',
    family: 'S',
  },
  // H-Family
  {
    id: 'kana-ha',
    hiraganaPath: './hiragana-ha.png',
    katakanaPath: './katakana-ha.png',
    name: 'ha',
    family: 'H',
  },
  {
    id: 'kana-hi',
    hiraganaPath: './hiragana-hi.svg',
    katakanaPath: './katakana-hi.png',
    name: 'hi',
    family: 'H',
  },
  {
    id: 'kana-fu',
    hiraganaPath: './hiragana-fu.svg',
    katakanaPath: './katakana-fu.png',
    name: 'fu',
    family: 'H',
  },
  {
    id: 'kana-he',
    hiraganaPath: './hiragana-he.svg',
    katakanaPath: './katakana-he.png',
    name: 'he',
    family: 'H',
  },
  {
    id: 'kana-ho',
    hiraganaPath: './hiragana-ho.svg',
    katakanaPath: './katakana-ho.png',
    name: 'ho',
    family: 'H',
  },
];
