export default [
  {
    id: 'kana-a',
    hiraganaPath: './hiragana-a.svg',
    katakanaPath: './katakana-a.svg',
    name: 'a',
    family: 'vowel',
  },
  {
    id: 'kana-i',
    hiraganaPath: './hiragana-i.svg',
    katakanaPath: './katakana-i.svg',
    name: 'i',
    family: 'vowel',
  },
  {
    id: 'kana-u',
    hiraganaPath: './hiragana-u.svg',
    katakanaPath: './katakana-u.svg',
    name: 'u',
    family: 'vowel',
  },
  {
    id: 'kana-e',
    hiraganaPath: './hiragana-e.svg',
    katakanaPath: './katakana-e.svg',
    name: 'e',
    family: 'vowel',
  },
  {
    id: 'kana-o',
    hiraganaPath: './hiragana-o.svg',
    katakanaPath: './katakana-o.svg',
    name: 'o',
    family: 'vowel',
  },
  {
    id: 'kana-ka',
    hiraganaPath: './hiragana-ka.svg',
    katakanaPath: './katakana-ka.svg',
    name: 'ka',
    family: 'K',
  },
  {
    id: 'kana-ki',
    hiraganaPath: './hiragana-ki.svg',
    katakanaPath: './katakana-ki.svg',
    name: 'ki',
    family: 'K',
  },
  {
    id: 'kana-ku',
    hiraganaPath: './hiragana-ku.svg',
    katakanaPath: './katakana-ku.svg',
    name: 'ku',
    family: 'K',
  },
  {
    id: 'kana-ke',
    hiraganaPath: './hiragana-ke.svg',
    katakanaPath: './katakana-ke.svg',
    name: 'ke',
    family: 'K',
  },
  {
    id: 'kana-ko',
    hiraganaPath: './hiragana-ko.svg',
    katakanaPath: './katakana-ko.svg',
    name: 'ko',
    family: 'K',
  },
  {
    id: 'kana-na',
    hiraganaPath: './hiragana-na.svg',
    katakanaPath: './katakana-na.svg',
    name: 'na',
    family: 'N',
  },
  {
    id: 'kana-ni',
    hiraganaPath: './hiragana-ni.svg',
    katakanaPath: './katakana-ni.svg',
    name: 'ni',
    family: 'N',
  },
  {
    id: 'kana-nu',
    hiraganaPath: './hiragana-nu.svg',
    katakanaPath: './katakana-nu.svg',
    name: 'nu',
    family: 'N',
  },
  {
    id: 'kana-ne',
    hiraganaPath: './hiragana-ne.svg',
    katakanaPath: './katakana-ne.svg',
    name: 'ne',
    family: 'N',
  },
  {
    id: 'kana-no',
    hiraganaPath: './hiragana-no.svg',
    katakanaPath: './katakana-no.svg',
    name: 'no',
    family: 'N',
  },
  {
    id: 'kana-ma',
    hiraganaPath: './hiragana-ma.svg',
    katakanaPath: './katakana-ma.svg',
    name: 'ma',
    family: 'M',
  },
  {
    id: 'kana-mi',
    hiraganaPath: './hiragana-mi.svg',
    katakanaPath: './katakana-mi.svg',
    name: 'mi',
    family: 'M',
  },
  {
    id: 'kana-mu',
    hiraganaPath: './hiragana-mu.svg',
    katakanaPath: './katakana-mu.svg',
    name: 'mu',
    family: 'M',
  },
  {
    id: 'kana-me',
    hiraganaPath: './hiragana-me.svg',
    katakanaPath: './katakana-me.svg',
    name: 'me',
    family: 'M',
  },
  {
    id: 'kana-mo',
    hiraganaPath: './hiragana-mo.svg',
    katakanaPath: './katakana-mo.svg',
    name: 'mo',
    family: 'M',
  },
];
